server:
  port: 8081

spring:
  application:
    name: ms-books-catalogue

#  datasource:
#    url: jdbc:h2:mem:bookcatalogue
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:postgresql://localhost:5432/bookcatalogue
    username: postgres
    password: password123
    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: create-drop  # Crea tablas al arrancar, las borra al cerrar
#    show-sql: true

  jpa:
    hibernate:
      ddl-auto: update  # Crea/actualiza tablas autom√°ticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    org.springframework.web: DEBUG

logging:
  level:
    org.hibernate.SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue